=== ComeIn-NRW/amb/draft/schemas/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "OER",
  "description": "This is a generic JSON schema for describing an Open Educational Resource with schema.org",
  "type": "object",
  "default": {
    "@context": [
      "https://w3id.org/kim/lrmi-profile/draft/context.jsonld",
      {
        "@language": "de"
      }
    ]
  },
  "properties": {
    "@context": {
      "$ref": "https://dini-ag-kim.github.io/lrmi-profile/draft/schemas/schemas/context-schema.json"
    },
    "id": {
      "$ref": "https://dini-ag-kim.github.io/lrmi-profile/draft/schemas/schemas/id.json"
    },
    "type": {
      "$ref": "https://dini-ag-kim.github.io/lrmi-profile/draft/schemas/schemas/type.json"
    },
    "name": {
      "$ref": "https://dini-ag-kim.github.io/lrmi-profile/draft/schemas/schemas/name.json"
    },
    "creator": {
      "$ref": "https://dini-ag-kim.github.io/lrmi-profile/draft/schemas/schemas/creator.json"
    },
    "description": {
      "$ref": "https://dini-ag-kim.github.io/lrmi-profile/draft/schemas/schemas/description.json"
    },
    "about": {
      "$ref": "https://dini-ag-kim.github.io/lrmi-profile/draft/schemas/schemas/about.json"
    },
    "license": {
      "$ref": "https://dini-ag-kim.github.io/lrmi-profile/draft/schemas/schemas/license.json"
    },
    "image": {
      "$ref": "https://dini-ag-kim.github.io/lrmi-profile/draft/schemas/schemas/image.json"
    },
    "dateCreated": {
      "$ref": "https://dini-ag-kim.github.io/lrmi-profile/draft/schemas/schemas/dateCreated.json"
    },
    "inLanguage": {
      "$ref": "https://dini-ag-kim.github.io/lrmi-profile/draft/schemas/schemas/inLanguage.json"
    },
    "publisher": {
      "$ref": "https://dini-ag-kim.github.io/lrmi-profile/draft/schemas/schemas/publisher.json"
    },
    "learningResourceType": {
      "$ref": "https://dini-ag-kim.github.io/lrmi-profile/draft/schemas/schemas/learningResourceType.json"
    },
    "audience": {
      "$ref": "https://dini-ag-kim.github.io/lrmi-profile/draft/schemas/schemas/audience.json"
    },
    "isBasedOn": {
      "$ref": "https://dini-ag-kim.github.io/lrmi-profile/draft/schemas/schemas/isBasedOn.json"
    },
    "mainEntityOfPage": {
      "$ref": "https://dini-ag-kim.github.io/lrmi-profile/draft/schemas/schemas/mainEntityOfPage.json"
    }
  },
  "required": [
    "@context",
    "id",
    "name"
  ]
}

=== ComeIn-NRW/amb/draft/examples/valid/tutory-example.json
{
    "@context": {
      "id": "@id",
      "type": "@type",
      "@vocab": "http://schema.org/",
      "skos": "http://www.w3.org/2004/02/skos/core#",
      "prefLabel": "skos:prefLabel",
      "inScheme": "skos:inScheme",
      "Concept": "skos:Concept"
    },
    "name": "Arbeitsblatt - Mon avenir - Französisch - tutory.de",
    "id": "https://www.tutory.de/w/fbbadf1a",
    "image": "https://www.tutory.de/worksheet/fbbadf1a-145a-463d-9a43-1ae9965c86b9.jpg?width=1000",
    "type": "CreativeWork",
    "creator": [
      {
        "name": "HerunterS",
        "type": "Person"
      }
    ],
    "description": "Französisch-Arbeitsblatt",
    "about": [
      {
        "id": "https://w3id.org/kim/hochschulfaechersystematik/n059",
        "prefLabel": {
          "de": "Französisch"
        },
        "type": "Concept",
        "inScheme": {
          "id": "https://w3id.org/kim/hochschulfaechersystematik/scheme"
        }
      }
    ],
    "license": "https://creativecommons.org/publicdomain/zero/1.0/legalcode",
    "dateCreated": "2019-07-03",
    "inLanguage": "fr",
    "publisher": [
      {
        "type": "Organization",
        "name": "Tutory",
        "id": "https://www.tutory.de"
      }
    ],
    "audience": [
      {
        "id": "http://purl.org/dcx/lrmi-vocabs/educationalAudienceRole/student",
        "prefLabel": {
          "en_us": "student"
        },
        "type": "Concept",
        "inScheme": {
          "id": "http://purl.org/dcx/lrmi-vocabs/educationalAudienceRole/"
        }
      }
    ]
  }

=== ComeIn-NRW/amb/draft/examples/valid/addingToContext.json
{
    "@context": [ 
      "https://w3id.org/kim/lrmi-profile/draft/context.jsonld",
      {"presentedAt": "http://purl.org/ontology/bibo/presentedAt"}
    ],
    "name": "Beispielkurs",
    "id": "https://example.org/oer",
    "type": "Course",
    "learningResourceType": {
      "id": "https://w3id.org/kim/hcrt/course"
    }
  }

=== ComeIn-NRW/amb/draft/examples/valid/learningResourceType.json
{
  "@context": {
    "id": "@id",
    "type": "@type",
    "@vocab": "http://schema.org/",
    "skos": "http://www.w3.org/2004/02/skos/core#",
    "prefLabel": "skos:prefLabel",
    "inScheme": "skos:inScheme",
    "Concept": "skos:Concept"
  },
  "name": "Beispielkurs",
  "id": "https://example.org/oer",
  "type": "Course",
  "learningResourceType": {
    "id": "https://w3id.org/kim/hcrt/course"
  }
}

=== ComeIn-NRW/amb/draft/examples/valid/schemaorg-context.json
{
  "@context": [
    "https://w3id.org/kim/amb/draft/context.jsonld",
    "https://schema.org",
    {
      "@language": "de"
    }
  ],
  "name": "Beispielkurs",
  "id": "https://example.org/oer",
  "type": [
    "LearningResource",
    "Course"
  ],
  "learningResourceType": [
    {
      "id": "https://w3id.org/kim/hcrt/course"
    }
  ]
}

=== ComeIn-NRW/amb/draft/examples/valid/additionalContext.json
{
    "@context": [ 
      "https://w3id.org/kim/lrmi-profile/draft/context.jsonld",
      "https://json-ld.org/contexts/person.jsonld"
    ],
    "name": "Beispielkurs",
    "id": "https://example.org/oer",
    "type": "Course",
    "learningResourceType": {
      "id": "https://w3id.org/kim/hcrt/course"
    }
  }
